shinyUI(
  
navbarPage("Wranglr 1.0.0",
  
  tabPanel("Sample information file",
           includeCSS("www/style.css"),
           
           h4("Validate sample information file:"),
           br(),
           fileInput("sample_input", "Input sample info file"),
           htmlOutput("format_check"),
           fluidRow(
             column(5,
                    htmlOutput("sample_warnings"),
                    htmlOutput("group_time"),
                    htmlOutput("summarize_data")),
             column(5,
                    htmlOutput("meta_warnings"),
                    textOutput("variables"))
           ),
           br(),
           h4("Randomize and add QC"),
           textInput("project_title", "Project title:"),
           uiOutput("project_code"),
           checkboxInput("save_code", "Save project code"),
           uiOutput("destination"),
           selectInput("sample_order", "Sample run order",
                       choices = c("Original" = "original",
                                   "Global Random" = "random_global",
                                   "Random within group" = "random_group"), selected = "random_global"),
           conditionalPanel(condition = "input.sample_order == 'random_group'",
                            uiOutput("grouping_column_choice")),
           conditionalPanel(condition = "input.sample_order != 'original'",
                            uiOutput("subject_id_column_choice")),
           radioButtons("sample_position_type", "Sample positioning type",
                        choices = c("96-well plate" = "well", "54-vial plate" = "vial")),
           selectInput("n_plates", "Number of plates available", choices = c(2, 3), selected = 2),
           selectInput("qc_int", "Number of samples before every QC:",
                       choices = c("No QC samples" = NA, 5, 10, 12, 15), selected = 12),
           checkboxGroupInput("modes", "Modes",
                              choices = c("HILIC neg" = "HILIC_neg","HILIC pos" = "HILIC_pos",
                                          "RP neg" = "RP_neg", "RP pos" = "RP_pos"),
                              selected = c("HILIC_neg", "HILIC_pos", "RP_neg", "RP_pos"),
                              inline = TRUE),
           br(),
           strong("Number of QC before beginning of mode:"),
           br(),br(),
           fluidRow(
             conditionalPanel(condition = "input.modes.includes('HILIC_neg')",
                              column(3,
                                     numericInput("qc_begin_hilicneg", "HILIC neg",
                                                 value = 10, min = 0, step = 1))),
             conditionalPanel(condition = "input.modes.includes('HILIC_pos')",
                              column(3,
                                     numericInput("qc_begin_hilicpos", "HILIC pos",
                                                  value = 10, min = 0, step = 1))),
             conditionalPanel(condition = "input.modes.includes('RP_neg')",
                              column(3,
                                     numericInput("qc_begin_rpneg", "RP neg",
                                                  value = 10, min = 0, step = 1))),
             conditionalPanel(condition = "input.modes.includes('RP_pos')",
                              column(3,
                                     numericInput("qc_begin_rppos", "RP pos",
                                                  value = 10, min = 0, step = 1)))
           ),
           br(),
           strong("QC sample position of mode:"),
           br(),br(),
           uiOutput("qc_poschars"),
           checkboxInput("add_automsms","Add AutoMSMS to Worklist files", value = TRUE),
           conditionalPanel(condition = "input.add_automsms == true",
                            checkboxInput("msms_qc","Run AutoMSMS on a QC sample", value = TRUE),
                            uiOutput("msms_samples")),
           actionButton("modify_sample", "Submit & Process"),
           br(),
           br(),
           uiOutput("randomize_column_warnings"),
           uiOutput("sample_mod_info"),
           br(),
           br()),
  
  tabPanel("Instructions",
           h4("Download Wranglr instructions"),
           downloadButton("instructions"),
           h4("Download sample information sheet specifications"),
           downloadButton("sample_specs"),
           h4("Download example sample information file"),
           downloadButton("sample_info"),
           h4("Download example sample information with repeated measurements"),
           downloadButton("repeated_measurements"),
           br(),
           br(),
           br(),
           h4("For developers:"),
           h5(capture.output(sessionInfo())[1]),
           h5("Installed packages:"),
           downloadButton("packages"))
))